from pathlib import Path
ROOT_DIR = Path(__file__).parent
OUTPUT_FOLDER_NAME = "__output"
DATALOADER = "data_loader"
BATCH_SIZE = "batch_size"
TRAIN, VALIDATION, TEST = "train", "validation", "test"
ID = "id"
NAME = "name"
NB_EPOCHS = "nb_epochs"
ARCHITECTURE = "architecture"
MODEL = "model"
NAME = "name"
N_PARAMS = "n_params"
OPTIMIZER = "optimizer"
LR = "lr"
PARAMS = "parameters"
